In [ ]:
import pandas as pd
import numpy as np
import datetime as dt
import matplotlib.pyplot as plt
%matplotlib inline
from matplotlib.pylab import rcParams
rcParams['figure.figsize']=20,10
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

In [ ]:
from google.colab import files
uploaded= files.upload()


In [ ]:
data = pd.read_csv('station_month.csv')


In [ ]:
data = data.dropna()

In [ ]:
data.head()

Station  Year  Month   Day  Night  DayLimit  NightLimit
0   BEN01  2011      2  66.0   56.0        55          45
1   BEN01  2011      3  66.0   58.0        55          45
2   BEN01  2011      4  66.0   57.0        55          45
3   BEN01  2011      5  66.0   56.0        55          45
4   BEN01  2011      6  67.0   57.0        55          45

In [ ]:
data.tail()

Station  Year  Month   Day  Night  DayLimit  NightLimit
5000   MUM10  2018      8  73.0   69.0        65          55
5001   MUM10  2018      9  72.0   68.0        65          55
5002   MUM10  2018     10  73.0   68.0        65          55
5003   MUM10  2018     11  72.0   68.0        65          55
5004   MUM10  2018     12  72.0   68.0        65          55

In [ ]:
data.describe()

Year        Month  ...     DayLimit   NightLimit
count  4995.000000  4995.000000  ...  4995.000000  4995.000000
mean   2015.198999     6.538338  ...    60.731732    51.543544
std       2.172580     3.434244  ...     8.770542    10.173202
min    2011.000000     1.000000  ...    50.000000    40.000000
25%    2014.000000     4.000000  ...    50.000000    40.000000
50%    2016.000000     7.000000  ...    65.000000    55.000000
75%    2017.000000    10.000000  ...    65.000000    55.000000
max    2018.000000    12.000000  ...    75.000000    70.000000

[8 rows x 6 columns]

In [ ]:
data.isnull().sum()

Station       0
Year          0
Month         0
Day           0
Night         0
DayLimit      0
NightLimit    0
dtype: int64

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X = data.iloc[:,[0,1,2,4]].values
y = data.iloc[:,3].values
print(X)
print(y)

[['BEN01' 2011 2 56.0]
 ['BEN01' 2011 3 58.0]
 ['BEN01' 2011 4 57.0]
 ...
 ['MUM10' 2018 10 68.0]
 ['MUM10' 2018 11 68.0]
 ['MUM10' 2018 12 68.0]]
[66. 66. 66. ... 73. 72. 72.]


In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()
X[:,0] = le.fit_transform(X[:,0])

In [ ]:
print(X)

[[0 2011 2 56.0]
 [0 2011 3 58.0]
 [0 2011 4 57.0]
 ...
 [69 2018 10 68.0]
 [69 2018 11 68.0]
 [69 2018 12 68.0]]


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=2)

In [ ]:
regr = LinearRegression()

In [ ]:
regr.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
pred = regr.predict(X_test)

In [ ]:
pred

array([55.16370595, 65.44357795, 73.86966503, ..., 72.18738058,
       59.64693079, 60.99129333])

In [ ]:
print(pred)

[55.16370595 65.44357795 73.86966503 ... 72.18738058 59.64693079
 60.99129333]


In [ ]:
regr.score(X_test, y_test)

0.8121257520233378

In [ ]:
from sklearn.ensemble import ExtraTreesRegressor

In [ ]:
reg1 = ExtraTreesRegressor(n_estimators=100, random_state=0).fit(X_train, y_train)


In [ ]:
reg1.score(X_test, y_test)

0.882688374401543

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
knn = KNeighborsClassifier(n_neighbors=3496)

In [ ]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3496, p=2,
                     weights='uniform')

In [ ]:
print(knn.score(X_test, y_test))

0.06004002668445631
